# Generated by Django 4.2.5 on 2023-09-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
