# Generated by Django 4.2.5 on 2023-09-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_catigory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catigory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.catigory'),
        ),
        migrations.AlterField(
            model_name='catigory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
